#!/bin/sh

# Modified from: http://tech.zumba.com/2014/04/14/control-code-quality/

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHPUnit..."
composer run test
if [ $? != 0 ]
then
    echo "Fix the errors before committing."
    exit 1
fi

echo "Checking PHP Lint..."
composer run lint
if [ $? != 0 ]
then
    echo "Fix the errors before committing."
    exit 1
fi

echo "Running Code Sniffer..."
composer run sniff
if [ $? != 0 ]
then
    echo "Fix the errors before committing."
    exit 1
fi

exit $?
